-- AlterEnum: Add missing TimelineEventType enum values
ALTER TYPE "TimelineEventType" ADD VALUE IF NOT EXISTS 'JOB_PIPELINE_REMOVED';
ALTER TYPE "TimelineEventType" ADD VALUE IF NOT EXISTS 'OUTREACH_TASK_CREATED';
ALTER TYPE "TimelineEventType" ADD VALUE IF NOT EXISTS 'START_FOLLOWUP_CREATED';
ALTER TYPE "TimelineEventType" ADD VALUE IF NOT EXISTS 'REVIEW_VERDICT_SET';
ALTER TYPE "TimelineEventType" ADD VALUE IF NOT EXISTS 'REPLAY_INBOUND_STARTED';
ALTER TYPE "TimelineEventType" ADD VALUE IF NOT EXISTS 'REPLAY_INBOUND_FINISHED';
ALTER TYPE "TimelineEventType" ADD VALUE IF NOT EXISTS 'MEDIA_RECEIVED';
ALTER TYPE "TimelineEventType" ADD VALUE IF NOT EXISTS 'VOICE_TRANSCRIBED';
ALTER TYPE "TimelineEventType" ADD VALUE IF NOT EXISTS 'MEDIA_LINKED_TO_TASK';
ALTER TYPE "TimelineEventType" ADD VALUE IF NOT EXISTS 'OPPORTUNITY_TASK_CREATED';
ALTER TYPE "TimelineEventType" ADD VALUE IF NOT EXISTS 'SETTINGS_PLAYBOOK_UPDATED';
ALTER TYPE "TimelineEventType" ADD VALUE IF NOT EXISTS 'OPEN_QUESTION_ADDED';
ALTER TYPE "TimelineEventType" ADD VALUE IF NOT EXISTS 'OPEN_QUESTION_RESOLVED';
ALTER TYPE "TimelineEventType" ADD VALUE IF NOT EXISTS 'OPEN_QUESTION_FOLLOWUP_CREATED';
ALTER TYPE "TimelineEventType" ADD VALUE IF NOT EXISTS 'TASK_MARKED_STUCK';
ALTER TYPE "TimelineEventType" ADD VALUE IF NOT EXISTS 'CSCS_VERIFICATION';
ALTER TYPE "TimelineEventType" ADD VALUE IF NOT EXISTS 'UNDERFILLED_URGENT_JOB';
ALTER TYPE "TimelineEventType" ADD VALUE IF NOT EXISTS 'DORMANT_CANDIDATES_MATCH_URGENT_JOB';
ALTER TYPE "TimelineEventType" ADD VALUE IF NOT EXISTS 'FOLLOW_UP_AFTER_OFFER';
ALTER TYPE "TimelineEventType" ADD VALUE IF NOT EXISTS 'DAY1_AFTERCARE_CHECKIN';

