/**
 * Explainability types for AI suggestions and task creation
 * Shared between frontend and backend
 * 
 * Provides transparency into why the system made certain decisions,
 * increasing operator confidence and reducing rejection/edit rates.
 */

import { z } from "zod";

/**
 * Explainability object for AI-generated actions and task suggestions
 * 
 * This object explains:
 * - Why the action was suggested (rationale)
 * - What facts were used (usedFacts)
 * - What information is missing (missingInfo)
 * - What alternatives were considered (alternatives)
 * - Level of confidence and risk
 */
export interface Explainability {
  /** Risk level of the suggested action */
  riskLevel: "LOW" | "MEDIUM" | "HIGH";

  /** Bullet points explaining why this action was suggested (max 4) */
  rationale: string[];

  /** Facts from conversation/memory that were used in decision (max 8) */
  usedFacts: string[];

  /** Optional note about uncertainty (max 140 chars) */
  uncertainty: string | null;

  /** Information that would improve the suggestion (max 6) */
  missingInfo: string[];

  /** Alternative actions considered (max 2) */
  alternatives: Array<{
    action: string;
    reason: string;
  }>;

  /** Optional confidence score (0-1) */
  confidence?: number;

  /** Whether this was generated by AI or deterministic rules */
  generatedBy: "AI" | "RULES";

  /** ISO timestamp when explainability was generated */
  generatedAt: string;
}

/**
 * Zod schema for validating and sanitizing Explainability objects
 */
export const ExplainabilitySchema = z.object({
  riskLevel: z.enum(["LOW", "MEDIUM", "HIGH"]),
  rationale: z
    .array(z.string().trim())
    .max(4)
    .transform((arr) => arr.filter((s) => s.length > 0).slice(0, 4)),
  usedFacts: z
    .array(z.string().trim())
    .max(8)
    .transform((arr) => arr.filter((s) => s.length > 0).slice(0, 8)),
  uncertainty: z
    .string()
    .trim()
    .max(140)
    .nullable()
    .transform((val) => (val && val.length > 0 ? val : null)),
  missingInfo: z
    .array(z.string().trim())
    .max(6)
    .transform((arr) => arr.filter((s) => s.length > 0).slice(0, 6)),
  alternatives: z
    .array(
      z.object({
        action: z.string().trim(),
        reason: z.string().trim(),
      })
    )
    .max(2)
    .transform((arr) =>
      arr
        .filter((item) => item.action.length > 0 && item.reason.length > 0)
        .slice(0, 2)
    ),
  confidence: z
    .number()
    .min(0)
    .max(1)
    .optional()
    .transform((val) => (val !== undefined && val >= 0 && val <= 1 ? val : undefined)),
  generatedBy: z.enum(["AI", "RULES"]),
  generatedAt: z.string().refine(
    (val) => {
      // Validate ISO timestamp format
      const date = new Date(val);
      return !isNaN(date.getTime());
    },
    { message: "Invalid ISO timestamp" }
  ),
});

/**
 * Sanitize and validate an Explainability object
 * 
 * This function:
 * - Truncates arrays to max length
 * - Trims strings
 * - Drops empty entries
 * - Validates types and constraints
 * - Returns a safe, consistent Explainability object
 * 
 * @param input - Raw explainability data (may be unsafe/partial)
 * @returns Sanitized Explainability object
 */
export function sanitizeExplainability(input: unknown): Explainability {
  // If input is already valid, return as-is
  if (typeof input === "object" && input !== null) {
    const parsed = ExplainabilitySchema.safeParse(input);
    if (parsed.success) {
      // Zod schema ensures all required fields are present after transformation
      return parsed.data as Explainability;
    }
  }

  // Otherwise, provide safe defaults and try to extract valid fields
  const now = new Date().toISOString();
  
  // Start with safe defaults
  let riskLevel: "LOW" | "MEDIUM" | "HIGH" = "LOW";
  let rationale: string[] = [];
  let usedFacts: string[] = [];
  let uncertainty: string | null = null;
  let missingInfo: string[] = [];
  let alternatives: Array<{ action: string; reason: string }> = [];
  let confidence: number | undefined = undefined;
  let generatedBy: "AI" | "RULES" = "RULES";
  let generatedAt: string = now;

  // Try to extract valid fields from input
  if (typeof input === "object" && input !== null) {
    const raw = input as Record<string, unknown>;

    // Risk level
    if (raw.riskLevel === "LOW" || raw.riskLevel === "MEDIUM" || raw.riskLevel === "HIGH") {
      riskLevel = raw.riskLevel;
    }

    // Rationale (array of strings, max 4)
    if (Array.isArray(raw.rationale)) {
      rationale = raw.rationale
        .filter((item): item is string => typeof item === "string")
        .map((s) => s.trim())
        .filter((s) => s.length > 0)
        .slice(0, 4);
    }

    // Used facts (array of strings, max 8)
    if (Array.isArray(raw.usedFacts)) {
      usedFacts = raw.usedFacts
        .filter((item): item is string => typeof item === "string")
        .map((s) => s.trim())
        .filter((s) => s.length > 0)
        .slice(0, 8);
    }

    // Uncertainty (string or null, max 140 chars)
    if (typeof raw.uncertainty === "string") {
      const trimmed = raw.uncertainty.trim();
      uncertainty = trimmed.length > 0 && trimmed.length <= 140 ? trimmed : null;
    } else if (raw.uncertainty === null || raw.uncertainty === undefined) {
      uncertainty = null;
    }

    // Missing info (array of strings, max 6)
    if (Array.isArray(raw.missingInfo)) {
      missingInfo = raw.missingInfo
        .filter((item): item is string => typeof item === "string")
        .map((s) => s.trim())
        .filter((s) => s.length > 0)
        .slice(0, 6);
    }

    // Alternatives (array of objects, max 2)
    if (Array.isArray(raw.alternatives)) {
      alternatives = raw.alternatives
        .filter(
          (item): item is { action: string; reason: string } =>
            typeof item === "object" &&
            item !== null &&
            typeof (item as any).action === "string" &&
            typeof (item as any).reason === "string"
        )
        .map((item) => ({
          action: (item as any).action.trim(),
          reason: (item as any).reason.trim(),
        }))
        .filter((item) => item.action.length > 0 && item.reason.length > 0)
        .slice(0, 2);
    }

    // Confidence (number 0-1)
    if (typeof raw.confidence === "number" && raw.confidence >= 0 && raw.confidence <= 1) {
      confidence = raw.confidence;
    }

    // Generated by
    if (raw.generatedBy === "AI" || raw.generatedBy === "RULES") {
      generatedBy = raw.generatedBy;
    }

    // Generated at (ISO timestamp)
    if (typeof raw.generatedAt === "string") {
      const date = new Date(raw.generatedAt);
      if (!isNaN(date.getTime())) {
        generatedAt = date.toISOString();
      }
    }
  }

  // Return complete Explainability object
  const result: Explainability = {
    riskLevel,
    rationale,
    usedFacts,
    uncertainty,
    missingInfo,
    alternatives,
    generatedBy,
    generatedAt,
  };

  // Add confidence only if provided
  if (confidence !== undefined) {
    result.confidence = confidence;
  }

  return result;
}

/**
 * Create a deterministic explainability object for fallback/rules-based actions
 * 
 * Use this when creating tasks via deterministic logic (not AI-generated).
 * 
 * @param options - Options for generating explainability
 * @returns Explainability object with generatedBy: "RULES"
 */
export function createRulesExplainability(options: {
  riskLevel: "LOW" | "MEDIUM" | "HIGH";
  rationale: string[];
  usedFacts?: string[];
  uncertainty?: string | null;
  missingInfo?: string[];
  alternatives?: Array<{ action: string; reason: string }>;
  confidence?: number;
}): Explainability {
  const now = new Date().toISOString();

  return sanitizeExplainability({
    riskLevel: options.riskLevel,
    rationale: options.rationale,
    usedFacts: options.usedFacts || [],
    uncertainty: options.uncertainty || null,
    missingInfo: options.missingInfo || [],
    alternatives: options.alternatives || [],
    confidence: options.confidence,
    generatedBy: "RULES",
    generatedAt: now,
  });
}

